name: Deploy to Server

on:
  push:
    branches: [ "main" ] # main 브랜치에 push 될 때만 실행
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server using SSH
        uses: appleboy/ssh-action@v1.0.3 # SSH 접속을 도와주는 플러그인
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.WHITE_USERNAME }}
          key: ${{ secrets.WHITE_KEY }}
          port: ${{ secrets.WHITE_PORT }}
          script: |
            REPO_URL="https://github.com/sc2bat/cs-quiz-app.git"
            TARGET_DIR="/home/apps/cs-quiz-app" 

            # 프로젝트 폴더로 이동
            cd $TARGET_DIR
            
            # 2. 최신 코드 받기
            git pull origin main
            
            # --- Backend ---
            echo "Deploying Backend..."
            cd server
            npm install
            npm run build
            pm2 restart quiz-api || pm2 start dist/app.js --name "quiz-api"
            
            # --- Frontend ---
            echo "Deploying Frontend..."
            cd ../client
            npm install
            npm run build
            
            echo "Deployment Finished!"